### PR TITLE
fix: make redirect option work

### PR DESCRIPTION
**Pull request by chriscalo**
I can only assume this is what was intended

### CODE REVIEW

**Comment by chriscalo** [comment]
I confirmed locally things work after this change and didn't work before the change when `config.redirect` is set.

**Comment by chriscalo** [comment]
Thanks for merging. Do you plan in publishing a new version to npm soon?

**Comment by vespaiach** [comment]
yes, will do soon. I'm getting stuck with npm 2FA, I've just enabled it and don't know how to deal with the publishing

**Comment by chriscalo** [comment]
Sounds good, don't rush on my account, I have a workaround in place for now and will check every few weeks to try to pull a newer version from npm. Thanks!

**Pull request merged**
